name:                quiz
version:             0.1.0.0

license:             BSD3
author:              Eli Peery
maintainer:          eli.g.peery@gmail.com
copyright:           "2020 Eli Peery"

extra-source-files:
- README.md
- CHANGELOG.md
- TODO.md

ghc-options:
- -O2
- -flate-specialise
- -fspecialise-aggressively
- -fplugin=Polysemy.Plugin
- -Wall
- -Wno-unused-binds
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmissing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef
- -Wmissing-export-lists

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
  - base >=4.12 && <4.13
  - text
  - containers
  - polysemy
  - polysemy-plugin
  - polysemy-zoo
  - servant
  - servant-server
  - aeson
  - warp
  - wai
  - wai-cors
  - wai-extra
  - optparse-generic
  - bytestring
  - mtl
  - blaze-html
  - blaze-markup
  - servant-JuicyPixels
  - JuicyPixels
  - uuid
  - turtle

library:
  source-dirs: src

executables:
  quiz-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quiz
